### ISSUE TITLE
Add support for userdata type.

### ISSUE THREAD

**Issue by luisalcarasr** [thibthib18/mongo-nvim#2]
During the generation of the preview an error appears, it seems that it cannot handle the "array".
**NOTE:** I have tried to use `_id` as `list_document_key`.
```log
E5108: Error executing lua .../start/mongo-nvim/lua/mongo-nvim/telescope/previewer.lua:36: Cannot convert userdata
stack traceback:
        [C]: in function 'nvim_buf_set_lines'
```

**Comment by thibthib18** [comment]
Hi, I finally got a bit of time to look at this. Now `_id` key can be used properly. It will also now be the default key as this is the only key present for any document.

The issue was that the id isn't a string, but a BSON.ObjectID and needs to be handled differently.
